export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const PERSIST_MESSAGE = 'PERSIST_MESSAGE';
export const PERSIST_MESSAGE_SUCCESS = 'PERSIST_MESSAGE_SUCCESS';
export const PERSIST_MESSAGE_FAILED = 'PERSIST_MESSAGE_FAILED';
